name: DesertGenerator  
main: com.github.minetonight.desertgenerator.DesertGenerator
version: 0.1
website: http://www.minecraftskinsserver.wordpress.com
author: minetonight
description: Custom world generator for Bukkit. Creates desert island.
load: startup
depend: [MetroSystemGenerator]